name: PR Agent

on:
  issue_comment:
    types: [created]

permissions:
  contents: write      # Required for auto-fix: create branches and commit files
  issues: write        # Required for posting comments
  pull-requests: write # Required for creating PRs

jobs:
  review:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@agent')
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Run PR Agent
        uses: parimalpate123/pr-code-review-action@justbedrock
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          model: us.anthropic.claude-3-5-haiku-20241022-v1:0
          bedrock_region: us-east-1
          max_tokens: "25000"
          timeout_minutes: "30"
